openapi: 3.0.0
info:
  description: >
    For the latest release information please check our [release notes](https://developer.myoperato.com/release_notes).
    The Operato Fnb API exposes integrations endpoint and related functions.
  version: 'unstable'
  title: 'Operato Fnb'
  termsOfService: 'https://myoperato.com/terms/'
  contact:
    email: 'heartyoh@hatiolab.com'
  license:
    name: MIT
    url: http://mit-license.org/
tags:
  - name: 'operato-fnb'
    description: 'API for read, create and update operato-fnbs'
schemes:
  - 'https'
  - 'http'
servers:
  - url: '/api/unstable'

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    bearerAuth:
      type: http
      scheme: bearer

security:
  - basicAuth: []
  - bearerAuth: []
responses:
  UnauthorizedError:
    description: Unauthorized

externalDocs:
  description: 'Find out about our release notes'
  url: 'https://developer.myoperato.com/release_notes'
